### PR TITLE
histogram pointer added

### PR DESCRIPTION
**Pull request by pfrechFra**
Right now there is no working option to set the pointer via chart.js, but the workaround over css should do the job for now

### CODE REVIEW

**Comment by pfrechFra** [comment]
#112

**Comment by antonroesler** [comment]
Now you are doing it on the whole sidebar (on every tab), or not?

**Comment by pfrechFra** [comment]
only at the lower box

**Comment by antonroesler** [comment]
That's not good. Only on the diagram.

**Comment by pfrechFra** [comment]
ok, changed that

**Comment by antonroesler** [comment]
That looks better 👍🏻

**Pull request merged**
