### PR TITLE
Create README2.md

### PR DESCRIPTION
**Pull request by pfrechFra**
New Folder + description

### CODE REVIEW

**Comment by antonroesler** [comment]
It would be cool if you create a separate folder for each of us in the prototypes folder, where everyone then creates their prototype. And come up with something better than the name README2.md

**Comment by pfrechFra** [comment]
Will do so ;)

**Comment by antonroesler** [comment]
great

**Comment by antonroesler** [comment]
I also ment the name "README2", give it a better name like "Prototype Description" or something. There should be only one read me

**Comment by pfrechFra** [comment]
take a closer look, it is called "How_To"

**Pull request merged**
